default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff-format
        args: [ ., --check ]
      - id: ruff-format
        args: [ . ]
      - id: ruff
        args: [ ., --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.396
    hooks:
      - id: pyright
