name: Python Code Quality
on: [ push, pull_request ]
jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Linting
        run: uv run ruff check .
      
      - name: Formatting
        run: uv run ruff format --check .
      
      - name: Type Consistency
        run: uv run pyright .